[project]
name = "tube-recipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.93.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "youtube-transcript-api>=1.1.1",
    "yt-dlp>=2025.6.30",
]
